#!/bin/bash

## Default
TRACKED_USER=$(ls -1 /home | head -1)
TRACKED_USER_LOG_DIR="/var/log/users"

function usage {
	cat << EOF
usage: $0 options
	I log the presence of a given user.
        
	Example use (using cron):
	
		$ # Edit cron config file:
		$ crontab -e
		# Add the following line:
		0 * * * * /usr/local/bin/log_user --user=yourusername

	Example use (without cron)

		log_user --user=yourusername

OPTIONS:
   --user  	Username of user you wish to monitor (Default: $TRACKED_USER)
   --log-dir  	Directory in which to save user logs (Default: $TRACKED_USER_LOG_DIR)
   -h|--help    Show this message
EOF
}

# Parse flags:
while [ "$#" -gt 0 ]; do
  case "$1" in
    --user=*)
        TRACKED_USER="${1#*=}";
        shift 1;;

   --log-dir=*)
        TRACKED_USER_LOG_DIR="${1#*=}";
        shift 1;;

    --help|-h)
        usage >&2;
        exit 1;;

    *)
        echo "Unknown option: $1";
        usage >&2;
        exit 1;;
  esac
done

## Helper functions
function init_directory_structure {
	mkdir -p $TRACKED_USER_LOG_DIR/$TRACKED_USER/
}

function is_user_logged_in {
	local username=$1

	local is_present=$(who | grep "$username" | wc -l)
	
	# Get login session name of user
	local session_name=$(loginctl | grep $TRACKED_USER | awk '{print($1)}')
	# Check if screen is locked
	local is_locked=$(loginctl show-session -p IdleHint $session_name | grep yes | wc -l)
	
	if test $is_present -gt 0 && test $is_locked -eq 0 ; 
	then
		is_logged_in=1
	else
		is_logged_in=0
	fi

	echo $is_logged_in
	return 0
}

function track_user {
	local year=$(date +%Y)
	local month=$(date +%B)
	local week=$(date +%U)
	local day=$(date +%A)
	local hour=$(date +%H)
	local minute=$(date +%M)
	local presence_str="Unknown"

	if [ $(is_user_logged_in) -eq 1 ]
	then
		presence="Present" 
	else
		presence="Absent"
	fi
	
	printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
		$year \
		$month \
		$week \
		$day \
		$hour \
		$minute \
		$presence \
		>> $TRACKED_USER_LOG_DIR/$TRACKED_USER/presence.log
}

init_directory_structure
track_user $TRACKED_USER

